name: rizq
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.13.0'

#--------------- PACKAGES ------------------#
dependency_overrides:
  web: ^1.0.0 # Force newer web package
  firebase_core: ^3.0.0 # Force newer core

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0
  image_picker: ^1.0.7
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

  # QR Code & Camera
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.10
  # qr_code_scanner: ^1.0.1
  # camera: ^0.10.6

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5

  firebase_auth: ^5.5.3

  qr_code_scanner_plus: ^2.0.10+1
  # Consider adding firebase_messaging if notifications are needed later
  #--------------- ./ PACKAGES END ------------------#

  # New packages
  syncfusion_flutter_charts: ^29.1.39
  pdf: ^3.10.8
  csv: ^6.0.0
  responsive_builder: ^0.7.0
  file_picker: ^10.1.2
  firebase_app_check: ^0.3.2+5
  device_preview: ^1.2.0
  rename_app: ^1.6.3
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FF65C3"
  adaptive_icon_foreground: "assets/icons/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  fullscreen: true
  image: assets/icons/splash.png
  image_dark: assets/icons/splash.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: assets/icons/splash.png
    image_dark: assets/icons/splash.png
  web: false
