// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQ93M7PuzUh--NtrKb_xTo8Z4TMtHY7s',
    appId: '1:317164897608:android:058ec7575b46ce16bc9f7d',
    messagingSenderId: '317164897608',
    projectId: 'connect-49e65',
    databaseURL: 'https://connect-49e65-default-rtdb.firebaseio.com',
    storageBucket: 'connect-49e65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hUF9FGPC9KjYAjLht7KCc08HGeqS9Dk',
    appId: '1:317164897608:ios:9e19ef6a88cccbdbbc9f7d',
    messagingSenderId: '317164897608',
    projectId: 'connect-49e65',
    databaseURL: 'https://connect-49e65-default-rtdb.firebaseio.com',
    storageBucket: 'connect-49e65.appspot.com',
    androidClientId: '317164897608-cqldicl89caaikln4j7ehituhij3rss2.apps.googleusercontent.com',
    iosClientId: '317164897608-oecpenh4j8m3i2civ97sh7v4r443qcph.apps.googleusercontent.com',
    iosBundleId: 'com.ri.zq.rizq',
  );
}
