name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'web/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build web (Normal Mode)
      run: flutter build web --release --no-tree-shake-icons --base-href "/rizq_u_project/" --dart-define=CI=true
      env:
        # Disable Firebase App Check for CI/CD to avoid reCAPTCHA issues
        FLUTTER_WEB_USE_SKIA: true
        CI: true
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web 