name: iOS-ipa-build-comprehensive

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build (Comprehensive)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.32.5'

      - name: Show Flutter version
        run: flutter --version

      - name: Show Flutter doctor
        run: flutter doctor -v

      - name: Clean project
        run: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -f ios/Podfile.lock
          rm -rf build
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Flutter precache iOS
        run: flutter precache --ios

      - name: Setup iOS dependencies
        run: |
          cd ios
          # Update minimum deployment target in iOS project files before pod install
          # mobile_scanner 6.0.10 requires iOS 15.5 minimum
          find . -name "*.xcconfig" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 11.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.xcconfig" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.xcconfig" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.xcconfig" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.xcconfig" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          find . -name "*.pbxproj" -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14.0/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' {} \;
          # Update Podfile to ensure minimum deployment target
          if ! grep -q "platform :ios" Podfile; then
            echo "platform :ios, '15.5'" > Podfile.tmp
            cat Podfile >> Podfile.tmp
            mv Podfile.tmp Podfile
          else
            sed -i '' "s/platform :ios, '[^']*'/platform :ios, '15.5'/g" Podfile
          fi
          pod repo update
          pod install --repo-update
          # Ensure Flutter framework is available after pod install
          if [ ! -d "Flutter" ]; then
            echo "Creating Flutter directory"
            mkdir -p Flutter
          fi
          cd ..

      - name: Prepare iOS build environment
        run: |
          # Ensure Flutter can find iOS toolchain
          flutter doctor -v
          # Generate Flutter.framework if needed
          cd ios && xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -showBuildSettings | grep FLUTTER_ROOT || echo "Flutter root not found"
          cd ..

      - name: Build iOS IPA
        run: |
          # Set up Flutter environment
          export FLUTTER_ROOT="${FLUTTER_HOME:-$HOME/flutter}"
          export PATH="$FLUTTER_ROOT/bin:$PATH"
          
          # Build iOS IPA directly (this handles framework linking better)
          flutter build ipa --release --no-codesign --verbose

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/rizq.ipa
          tag: v1.0
          overwrite: true
          body: "iOS IPA build - $(date)" 