name: Build iOS App

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'ios/**'
      - '.github/workflows/ios-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'ios/**'

jobs:
  build-ios:
    runs-on: macos-latest
    name: Build iOS App

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: |
        flutter pub get --verbose
        flutter pub deps
    
    - name: Clean iOS build
      run: |
        cd ios
        rm -rf Pods Podfile.lock
        rm -rf ~/Library/Developer/Xcode/DerivedData
        cd ..
    
    - name: Setup iOS
      run: |
        cd ios
        # Ensure Podfile has correct platform version
        if ! grep -q "platform :ios, '15.5'" Podfile; then
          sed -i '' 's/platform :ios, '\''13.0'\''/platform :ios, '\''15.5'\''/' Podfile
        fi
        # Install pods with verbose output
        pod install --repo-update --verbose
        cd ..
    
    - name: Build iOS
      run: |
        flutter clean
        flutter pub get
        flutter build ios --release --no-codesign --dart-define=CI=true --verbose
      env:
        CI: true
        FLUTTER_BUILD_NUMBER: ${{ github.run_number }}
    
    - name: Upload iOS build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ios-build-${{ github.run_number }}
        path: build/ios/iphoneos/Runner.app
        retention-days: 30 