name: iOS-ipa-build-alternative

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build (Alternative)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.32.5'

      - name: Show environment info
        run: |
          echo "Flutter version:"
          flutter --version
          echo "Dart version:"
          dart --version
          echo "Xcode version:"
          xcodebuild -version

      - name: Clean everything
        run: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -f ios/Podfile.lock
          rm -rf build
          rm -rf .dart_tool
          rm -rf .flutter-plugins
          rm -rf .flutter-plugins-dependencies

      - name: Get dependencies
        run: |
          flutter pub get
          flutter pub deps

      - name: Setup iOS step by step
        run: |
          cd ios
          echo "Updating pod repo..."
          pod repo update
          echo "Installing pods..."
          pod install --repo-update --verbose
          echo "Verifying pod installation..."
          pod install --verbose
          cd ..

      - name: Pre-build iOS
        run: |
          flutter build ios --debug --no-codesign

      - name: Build iOS release
        run: |
          flutter build ios --release --no-codesign --verbose

      - name: Create IPA
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS IPA build - $(date)" 