name: iOS-ipa-build-simple

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build (Simple)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.32.5'

      - name: Show Flutter version
        run: flutter --version

      - name: Clean project
        run: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -f ios/Podfile.lock

      - name: Get dependencies
        run: flutter pub get

      - name: Setup iOS
        run: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -qq -r -9 FlutterIpaExport.ipa Payload

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS IPA build - $(date)" 